"""create table todos

Revision ID: 00e70d137472
Revises: c3fe829872f7
Create Date: 2024-09-03 13:20:13.799313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import func


# revision identifiers, used by Alembic.
revision: str = '00e70d137472'
down_revision: Union[str, None] = 'c3fe829872f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=250), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime, default=func.now(), nullable=True),
    sa.Column('updated_at', sa.DateTime, default=func.now(), onupdate=func.now(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_todos_title'), 'todos', ['title'], unique=False)


def downgrade() -> None:
    op.drop_index(op.f('ix_todos_title'), table_name='todos')
    op.drop_table('todos')


