"""create table users

Revision ID: c3fe829872f7
Revises: 6d5c1f6bf462
Create Date: 2024-09-03 13:01:07.628926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import func

# revision identifiers, used by Alembic.
revision: str = 'c3fe829872f7'
down_revision: Union[str, None] = '6d5c1f6bf462'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'users',
        sa.Column('id', sa.Integer, primary_key=True),
        sa.Column('username', sa.String(length=50)),
        sa.Column('email', sa.String(length=50), nullable=False, unique=True),
        sa.Column('password', sa.String(length=255), nullable=False),
        sa.Column('avatar', sa.String(length=250), nullable=True),
        sa.Column('refresh_token', sa.String(length=255), nullable=True),
        sa.Column('created_at', sa.DateTime, default=func.now(), nullable=True),
        sa.Column('updated_at', sa.DateTime, default=func.now(), onupdate=func.now()),
        sa.Column('role', sa.Enum('admin', 'moderator', 'user', name='role'), default='user', nullable=True),
        sa.Column('confirmed', sa.Boolean, default=False)

    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
